# SPDX-License-Identifier: MIT
---

# Validate manage timesync variables
- name: Ensure explicit DC provided with manage timesync is true
  fail:
    msg: "ad_integration_join_to_dc must be provided if manage timesync is true"
  when: ad_integration_manage_timesync | bool and ad_integration_join_to_dc is none

  # Validate manage crypto variables
- name: Ensure manage_crypt_policies is set with crypto_allow_rc4
  fail:
    msg: "ad_integration_manage_crypto_policies must be true if ad_integration_allow_rc4_crypto is true"
  when: ad_integration_allow_rc4_crypto | bool and not ad_integration_manage_crypto_policies | bool

- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Ensure required packages are installed
  package:
    name: "{{ __ad_integration_packages }}"
    state: present

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ __ad_integration_services }}"

- name: Generate /etc/{{ __ad_integration_realmd_config }}
  template:
    src: "{{ __ad_integration_realmd_config }}.j2"
    dest: /etc/{{ __ad_integration_realmd_config }}
    backup: yes
    mode: 0400
  notify: ad_integration handler to restart services

- name: Flush handlers
  meta: flush_handlers

## Execute other roles if applicable
- name: Manage timesync
  include_role:
   name: fedora.linux_system_roles.timesync
  vars:
    timesync_ntp_servers:
      - hostname:  "{{ ad_integration_join_to_dc }}"
        iburst: yes
  when: ad_integration_manage_timesync | bool

- name: Manage crypto policies
  include_role:
   name: fedora.linux_system_roles.crypto_policies
  vars:
    crypto_policies_policy: "DEFAULT:AD-SUPPORT"
  when:
    - ad_integration_manage_crypto_policies | bool
    # Fedora and RHEL8+
    - (ansible_distribution == "Fedora" or (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_version is version('8', '>=')))

## RHEL9 uses the AD-SUPPORT-LEGACY policy for RC4, otherwise AD-SUPPORT allows it
- name: Enable crypto policy allowing RC4 encryption
  include_role:
   name: fedora.linux_system_roles.crypto_policies
  vars:
    crypto_policies_policy: "DEFAULT:AD-SUPPORT-LEGACY"
  when:
    - ad_integration_allow_rc4_crypto | bool
    - ansible_distribution in ['CentOS', 'RedHat']
    - ansible_distribution_version is version('9', '>=')

- name: Join to a specific Domain Controller
  shell: echo {{ ad_integration_password }} | realm join -U {{ ad_integration_user }} --membership-software {{ ad_integration_membership_software }} {{ ad_integration_join_to_dc }}
  when:
    - ad_integration_join_to_dc is not none
    - not ansible_check_mode

- name: Perform discovery-based realm join operation
  shell: echo {{ ad_integration_password }} | realm join -U {{ ad_integration_user }} --membership-software {{ ad_integration_membership_software }} {{ ad_integration_realm }}
  when:
    - ad_integration_join_to_dc is none
    - not ansible_check_mode