# SPDX-License-Identifier: MIT
---

# join_to_dc is required if manage_timesync is true
- name: Ensure explicit DC provided with manage timesync is true
  fail:
    msg: "ad_integration_join_to_dc must be provided if manage timesync is true"
  when: ad_integration_manage_timesync | bool and ad_integration_join_to_dc is none

- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Ensure required packages are installed
  package:
    name: "{{ __ad_integration_packages }}"
    state: present

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ __ad_integration_services }}"

- name: Generate /etc/{{ __ad_integration_realmd_config }}
  template:
    src: "{{ __ad_integration_realmd_config }}.j2"
    dest: /etc/{{ __ad_integration_realmd_config }}
    backup: yes
    mode: 0400
  notify: ad_integration handler to restart services

- name: Flush handlers
  meta: flush_handlers

## Execute other roles if applicable
- name: Manage timesync
  include_role:
   name: fedora.linux_system_roles.timesync
  vars:
    timesync_ntp_servers:
      - hostname:  "{{ ad_integration_join_to_dc }}"
        iburst: yes
  when: ad_integration_manage_timesync | bool

- name: Join to a specific Domain Controller
  shell: echo {{ ad_integration_password }} | realm join -U {{ ad_integration_user }} --membership-software {{ ad_integration_membership_software }} {{ ad_integration_join_to_dc }}
  when: ad_integration_join_to_dc is not none

- name: Perform discovery-based realm join operation
  shell: echo {{ ad_integration_password }} | realm join -U {{ ad_integration_user }} --membership-software {{ ad_integration_membership_software }} {{ ad_integration_realm }}
  when: ad_integration_join_to_dc is none